# Configuration for release-drafter action
name: Release Drafter
on:
  push:
    branches:
      - main
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited

jobs:
  release-drafter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Release Drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-file: .github/release-drafter.yml
