name: Main Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: 'go'

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
