name: Main workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Run make cover
      run: make cover

    - name: Run make lint
      run: make lint

    - name: Run make format
      run: make format

    - name: Run make generate
      run: make generate

    - name: Run make tidy
      run: make tidy

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: 'go'

    - name: Run CodeQL analyze
      uses: github/codeql-action/analyze@v2
