# Copyright © 2023 OpenIM. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Release Drafter Action

on:
  push:
    # this list of branches is often enough,
    # but you may still ignore other public branches
    branches-ignore: [main, master, dev, development, release]

jobs:
  opencommit:
    timeout-minutes: 10
    name: OpenCommit
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Setup Node.js Environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: di-sukharev/opencommit@github-action-v1.0.4
        with:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}

        env:
          # set openAI api key in repo actions secrets,
          # for openAI keys go to: https://platform.openai.com/account/api-keys
          # for repo secret go to: <your_repo_url>/settings/secrets/actions
          RD_CONFIG: .github/release-drafter.yml
          GITHUB_TOKEN: ${{ secrets.RELEASE_DRAFTER_GH_TOKEN }}
          GITHUB_USER: openimsdk
          GITHUB_REPOSITORY: openim-docs
          RD_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

          # customization
          RD_OPENAI_MAX_TOKENS: 500
          RD_OPENAI_BASE_PATH: ''
          RD_DESCRIPTION: false
          RD_EMOJI: false
          RD_MODEL: gpt-3.5-turbo-16k
          RD_LANGUAGE: en
          RD_PROMPT_MODULE: conventional-commit
        continue-on-error: true