name: Pre-commit Hook

on:
  push:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run pre-commit hook
                run: scripts/githooks/pre-commit.sh
